NORTH = (0, -1)
NORTH_EAST = (1, -1)
EAST = (1, 0)
SOUTH_EAST = (1, 1)
SOUTH = (0, 1)
SOUTH_WEST = (-1, 1)
WEST = (-1, 0)
NORTH_WEST = (-1, -1)

U = NORTH
UR = NORTH_EAST
R = EAST
DR = SOUTH_EAST
D = SOUTH
DL = SOUTH_WEST
L = WEST
UL = NORTH_WEST

DIRECTIONS = [U, UR, R, DR, D, DL, L, UL]
DIR_CROSS = [U, R, D, L]
DIR_ANGLE = [UR, DR, DL, UL]
